'use client';

import { useState, FormEvent } from 'react';
import { supabase } from '@/lib/supabase';

type Purpose = 'test' | 'donate' | 'notify';
type DeviceType = 'ios' | 'android';

const REFERRAL_OPTIONS = [
  'Social Media (Twitter / Instagram)',
  'Friend or Family',
  'Gurdwara Sangat',
  'Search Engine',
  'YouTube',
  'Reddit / Forum',
  'Other',
];

export default function WaitlistForm() {
  const [firstName, setFirstName] = useState('');
  const [email, setEmail] = useState('');
  const [purpose, setPurpose] = useState<Purpose | null>(null);
  const [deviceType, setDeviceType] = useState<DeviceType | null>(null);
  const [phoneWhatsapp, setPhoneWhatsapp] = useState('');
  const [referralSource, setReferralSource] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      // Validate required fields based on purpose
      if (!purpose) {
        setError("Please select how you'd like to participate.");
        setLoading(false);
        return;
      }

      if (purpose === 'test' && !deviceType) {
        setError('Please select your device type.');
        setLoading(false);
        return;
      }

      if (purpose === 'donate' && !phoneWhatsapp) {
        setError('Please provide your phone/WhatsApp number.');
        setLoading(false);
        return;
      }

      // Check if email already exists
      const { data: existing } = await supabase
        .from('user_profiles')
        .select('email')
        .eq('email', email)
        .single();

      if (existing) {
        setError('This email is already on the waitlist!');
        setLoading(false);
        return;
      }

      // Insert new user profile (referral_code auto-generated by trigger)
      const { error: insertError } = await supabase
        .from('user_profiles')
        .insert([
          {
            first_name: firstName,
            email,
            is_tester: purpose === 'test',
            is_donor: purpose === 'donate',
            device_ios: purpose === 'test' ? deviceType === 'ios' : null,
            phone_whatsapp: purpose === 'donate' ? phoneWhatsapp : null,
            referral_source: referralSource || null,
          },
        ]);

      if (insertError) throw insertError;

      setSuccess(true);
      setFirstName('');
      setEmail('');
      setPurpose(null);
      setDeviceType(null);
      setPhoneWhatsapp('');
      setReferralSource('');
    } catch (err: unknown) {
      console.error('Error joining waitlist:', err);
      const message =
        err instanceof Error ? err.message : 'Something went wrong. Please try again.';
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  if (success) {
    return (
      <div className="max-w-xl mx-auto">
        <div className="bg-white border-2 border-[#FF9933] rounded-2xl p-8 md:p-10 text-center">
          <div className="w-16 h-16 rounded-full bg-[#FF9933]/10 flex items-center justify-center mx-auto mb-4">
            <span className="text-3xl">&#x262C;</span>
          </div>
          <h3 className="text-2xl font-bold text-[#000080] mb-3">
            Thank you for joining!
          </h3>
          <p className="text-gray-700 mb-6">
            We will be in touch soon. Your support means everything to this seva
            project.
          </p>
          <div className="bg-[#000080]/5 rounded-xl p-6 text-left">
            <p className="gurmukhi-lg text-[#000080] font-semibold mb-2">
              ਆਨੰਦੁ ਭਇਆ ਮੇਰੀ ਮਾਏ ਸਤਿਗੁਰੂ ਮੈ ਪਾਇਆ ॥
            </p>
            <p className="text-gray-600 italic text-sm mb-1">
              Aanand bha-i-aa meree maa-e Satguroo mai paa-i-aa.
            </p>
            <p className="text-gray-700 text-sm">
              &ldquo;I am in ecstasy, O my mother! I have found my True
              Guru.&rdquo;
            </p>
            <p className="text-gray-400 text-xs mt-2">
              Sri Guru Granth Sahib Ji, Ang 917
            </p>
          </div>
          <p className="mt-6 text-[#000080] font-semibold">
            Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!
          </p>
        </div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="max-w-xl mx-auto">
      <div className="bg-white rounded-2xl shadow-xl p-8 space-y-6">
        {/* First Name */}
        <div>
          <label
            htmlFor="firstName"
            className="block text-sm font-semibold text-[#000080] mb-2"
          >
            First Name *
          </label>
          <input
            type="text"
            id="firstName"
            required
            value={firstName}
            onChange={(e) => setFirstName(e.target.value)}
            className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-[#FF9933] focus:outline-none transition"
            placeholder="Your first name"
          />
        </div>

        {/* Email */}
        <div>
          <label
            htmlFor="email"
            className="block text-sm font-semibold text-[#000080] mb-2"
          >
            Email Address *
          </label>
          <input
            type="email"
            id="email"
            required
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-[#FF9933] focus:outline-none transition"
            placeholder="your@email.com"
          />
        </div>

        {/* How did you hear about us? */}
        <div>
          <label
            htmlFor="referralSource"
            className="block text-sm font-semibold text-[#000080] mb-2"
          >
            How did you hear about us?
          </label>
          <select
            id="referralSource"
            value={referralSource}
            onChange={(e) => setReferralSource(e.target.value)}
            className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-[#FF9933] focus:outline-none transition text-gray-700"
          >
            <option value="">Select an option</option>
            {REFERRAL_OPTIONS.map((option) => (
              <option key={option} value={option}>
                {option}
              </option>
            ))}
          </select>
        </div>

        {/* Purpose Selection */}
        <div>
          <label className="block text-sm font-semibold text-[#000080] mb-3">
            I want to: *
          </label>
          <div className="space-y-3">
            <label className="flex items-start cursor-pointer">
              <input
                type="radio"
                name="purpose"
                value="test"
                checked={purpose === 'test'}
                onChange={(e) => setPurpose(e.target.value as Purpose)}
                className="mt-1 w-5 h-5 text-[#FF9933] border-gray-300 focus:ring-[#FF9933]"
              />
              <span className="ml-3 text-sm text-gray-700">
                <strong>Help test</strong> or contribute to development
              </span>
            </label>

            <label className="flex items-start cursor-pointer">
              <input
                type="radio"
                name="purpose"
                value="donate"
                checked={purpose === 'donate'}
                onChange={(e) => setPurpose(e.target.value as Purpose)}
                className="mt-1 w-5 h-5 text-[#FF9933] border-gray-300 focus:ring-[#FF9933]"
              />
              <span className="ml-3 text-sm text-gray-700">
                <strong>Donate time or resources</strong> to the project
              </span>
            </label>

            <label className="flex items-start cursor-pointer">
              <input
                type="radio"
                name="purpose"
                value="notify"
                checked={purpose === 'notify'}
                onChange={(e) => setPurpose(e.target.value as Purpose)}
                className="mt-1 w-5 h-5 text-[#FF9933] border-gray-300 focus:ring-[#FF9933]"
              />
              <span className="ml-3 text-sm text-gray-700">
                <strong>Be notified</strong> when the product is ready to use
              </span>
            </label>
          </div>
        </div>

        {/* Conditional: Device Type (for testers) */}
        {purpose === 'test' && (
          <div className="animate-fadeIn">
            <label
              htmlFor="deviceType"
              className="block text-sm font-semibold text-[#000080] mb-2"
            >
              Primary Device *
            </label>
            <select
              id="deviceType"
              required
              value={deviceType || ''}
              onChange={(e) => setDeviceType(e.target.value as DeviceType)}
              className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-[#FF9933] focus:outline-none transition"
            >
              <option value="">Select your device</option>
              <option value="ios">iOS (iPhone/iPad)</option>
              <option value="android">Android</option>
            </select>
          </div>
        )}

        {/* Conditional: Phone/WhatsApp (for donors) */}
        {purpose === 'donate' && (
          <div className="animate-fadeIn">
            <label
              htmlFor="phoneWhatsapp"
              className="block text-sm font-semibold text-[#000080] mb-2"
            >
              Phone / WhatsApp Number *
            </label>
            <input
              type="tel"
              id="phoneWhatsapp"
              required
              value={phoneWhatsapp}
              onChange={(e) => setPhoneWhatsapp(e.target.value)}
              className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-[#FF9933] focus:outline-none transition"
              placeholder="+1 (555) 123-4567"
            />
          </div>
        )}

        {/* Error Message */}
        {error && (
          <div className="bg-red-50 border-2 border-red-200 rounded-lg p-4 text-red-700 text-sm">
            {error}
          </div>
        )}

        {/* Submit Button */}
        <button
          type="submit"
          disabled={loading}
          className="w-full bg-gradient-to-r from-[#FF9933] to-[#000080] text-white px-8 py-4 rounded-lg font-semibold hover:opacity-90 transition disabled:opacity-50"
        >
          {loading ? 'Joining...' : 'Join the Waitlist'}
        </button>

        <p className="text-xs text-gray-500 text-center">
          Free forever. No ads. No spam. Built as seva for the Sangat.
        </p>
      </div>
    </form>
  );
}
